name: Kalamazoo ACS
markdown: redcarpet
highlight: pygments
excerpt_separator: <!-- more -->

# # URL and path data for various links and redirects
# path: ""
# url: http://kaylee.artiosonline.com:4000
# # Apache paths
# path: /~mwolf/kacs
# url: http://kaylee.artiosonline.com/~mwolf/kacs
# url: http://127.0.0.1/~mwolf/kacs
# # Localhost
# path: ""
# url: http://127.0.0.1:4000
baseurl: ""

exclude: [makefile, README.md]

# for bootstrap col-xs-8 style classes
device: md

# Serve dynamic or pre-compiled content
debug: 'true'

# Make sure future posts and events are presented
future: true

# Name of current KACS chair
chair: Brian Eklov

# General inquiries e-mail address
email: ACSkzoo@gmail.com
# webmaster e-mail address
webmaster: webmaster@kalamazooacs.org
