name: Kalamazoo ACS
markdown: redcarpet
pygments: true
excerpt_separator: <!-- more -->
url: http://kaylee.artiosonline.com:4000

exclude: [makefile, README.md]

# for bootstrap col-xs-8 style classes
device: xs